version: "3"
services:
  front:
    build:
      context: .
      dockerfile: front_end_server/Dockerfile
    ports:
      - "5000:5000"
    networks:
      - bridge
    environment:
      - BE_NUM=1
      - HOST=0.0.0.0
      - HTTP_SERVER_PORT=5000
      - BRIDGE_PORT=5001
      - LOG_FILE=audit-log

  back:
    build:
      context: .
      dockerfile: back_end_server/Dockerfile
    depends_on:
      - front
    networks:
      - bridge
    environment:
      - CACHE_SIZE=0
      - FE_IP=front
      - FE_PORT=5001
      - LOCKS_POOL_SIZE=100

networks:
  bridge: